### ISSUE TITLE
IDE Timeout issue

### ISSUE THREAD

**Issue by BaharF** [hpcc-systems/ECLCloudIDE#28]
In CloudIDE, if user logs to CloudIDE and let is sit idle for x amount of time, the IDE logs-out the user in the background without showing any warnings, or redirecting the user to login page. 
So, if user returns to IDE after being idle for x minutes, the user will see the exact same page that was used last. If the users tries to continue to work, the IDE will just throw a timeout error, without doing anything else. At this point, user needs to refresh the page(CloudIDE) which would redirect him/her to login page to continue. 
Majority of IDE users are students and new to this system. To make the process easier, following needs to take place:

**If CloudIDE is idle for 60 min, it should redirect itself to login page automatically.**

Screen shots will be provided as soon as my IDE passes that x time.

//*********** Update:
CloudIDE was idle for ~16hrs and didn't logout.

**Comment by jeclrsg** [comment]
fixed by 4e8dac0

If a session is timed out, a user will now be redirected to the login page if they attempt to compile, run, etc a script or otherwise interact with the ui (opening scripts, change workspace, etc)
