### ISSUE TITLE
Module import from folders is not working

### ISSUE THREAD

**Issue by alfjjacob** [hpcc-systems/ECLCloudIDE#30]
Importing a module stored within a folder seems to be throwing errors when the script is executed. Syntax check works as expected. It looks like the Archive XML created does not include the module script and its folder. If the script is executed directly from the root folder, it works. 

https://ide.hpccsystems.com/workspaces/share/8594f8cc-613d-4cb4-b6a0-dc6bbf6d146a

**Comment by jeclrsg** [comment]
fixed by cbf59de4
