### ISSUE TITLE
Script rename issue

### ISSUE THREAD

**Issue by alfjjacob** [hpcc-systems/ECLCloudIDE#31]
At times, when a script is renamed, it shows a message "A script with this name already exists". IDE UI does not show any duplicate names in the UI though. This does not happen always. 

![ide-rename](https://user-images.githubusercontent.com/856877/113766055-02991580-96eb-11eb-97fe-5f75a550b39b.png)

**Comment by jeclrsg** [comment]
fixed by 6e933b8
