### ISSUE TITLE
Comments in scripts are ignored

### ISSUE THREAD

**Issue by alfjjacob** [hpcc-systems/ECLCloudIDE#32]
This was reported from KSU hackathon. When some lines in the script are commented out individually using keyboard shortcut Shift + /, they do not get ignored when the script is executed. However, if they are commented out individually using double forward slashes or a block comment /* */, the script lines are ignored while it is executed. 

Looks like Codemirror is not firing key events to update the script content when using those shortcuts.

**Comment by jeclrsg** [comment]
fixed by e624bca
